# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Perfil
    url: /
    weight: 10

  - name: Experiencia
    url: experience/
    weight: 20

  - name: Proyectos
    url: projects/
    weight: 30

  - name: Docencia
    url: courses/
    weight: 40

  - name: Publicaciones
    url: publication/
    weight: 50
